#!/usr/bin/env python3

"""Two-command orchestration for GB200 KVPool/EGM validation."""

from __future__ import annotations

import argparse
import ctypes
import json
import mmap
import os
import pathlib
import re
import resource
import secrets
import shlex
import signal
import socket
import subprocess
import time
import urllib.parse
import urllib.request
from collections.abc import Mapping

try:
    from scripts.gb200.egm_validation_common import (
        artifact_manifest,
        collect_rdma_counters,
        collect_route_snapshot,
        collect_system,
        build_route_evidence,
        config_digest,
        counter_delta,
        emit_evidence,
        free_port,
        metadata_delete,
        metadata_get,
        metadata_put,
        read_jsonl,
        route_address,
        summarize,
        visible_devices,
    )
except ModuleNotFoundError:
    from egm_validation_common import (  # type: ignore[no-redef]
        artifact_manifest,
        collect_rdma_counters,
        collect_route_snapshot,
        collect_system,
        build_route_evidence,
        config_digest,
        counter_delta,
        emit_evidence,
        free_port,
        metadata_delete,
        metadata_get,
        metadata_put,
        read_jsonl,
        route_address,
        summarize,
        visible_devices,
    )


ACTIVE_SESSION_KEY = "mooncake/gb200-validation/active"
DEFAULT_PAYLOADS = [128 * 1024**2, 512 * 1024**2, 1024**3, 2 * 1024**3]
RAW_PAYLOADS = [128 * 1024**2, 512 * 1024**2, 1024**3, 2 * 1024**3, 4 * 1024**3]
RAW_STREAMS = [1, 2, 4, 8]
RDMA_BLOCKS = [64 * 1024, 1024**2, 8 * 1024**2]
RDMA_THREADS = [1, 4, 8]
RDMA_TARGET_READY_MARKER = "MOONCAKE_TRANSFER_ENGINE_BENCH_TARGET_READY"


def run(
    command: list[str],
    *,
    env: Mapping[str, str] | None = None,
    stdout=None,
    stderr=None,
    check: bool = True,
    cwd: pathlib.Path | None = None,
) -> subprocess.CompletedProcess[str]:
    print("+ " + shlex.join(command), flush=True)
    return subprocess.run(
        command,
        check=check,
        text=True,
        env=dict(env) if env is not None else None,
        stdout=stdout,
        stderr=stderr,
        cwd=cwd,
    )


def git_value(repo_root: pathlib.Path, *args: str) -> str:
    return subprocess.check_output(
        ["git", "-C", str(repo_root), *args], text=True
    ).strip()


def write_config(path: pathlib.Path, values: Mapping[str, object]) -> None:
    lines = ["# Generated by egm_store_orchestrator.py; do not edit during a run."]
    for name, value in values.items():
        if isinstance(value, str):
            lines.append(f"{name}={shlex.quote(value)}")
        else:
            lines.append(f"{name}={value}")
    path.write_text("\n".join(lines) + "\n")


def wait_process_log_marker(
    process: subprocess.Popen[str],
    log_path: pathlib.Path,
    marker: str,
    label: str,
    timeout: float = 60,
) -> None:
    deadline = time.monotonic() + timeout
    log_text = ""
    while time.monotonic() < deadline:
        if log_path.exists():
            log_text = log_path.read_text(errors="replace")
            if marker in log_text:
                return
        returncode = process.poll()
        if returncode is not None:
            raise RuntimeError(
                f"{label} exited rc={returncode} before readiness marker; "
                f"log tail:\n{log_text[-4096:]}"
            )
        time.sleep(0.5)
    raise RuntimeError(
        f"{label} did not emit readiness marker within {timeout:g}s; "
        f"log tail:\n{log_text[-4096:]}"
    )


def stop_process(
    process: subprocess.Popen[str] | None, label: str
) -> dict[str, object]:
    if process is None:
        return {"label": label, "status": "NOT_STARTED"}
    if process.poll() is None:
        process.terminate()
        try:
            process.wait(timeout=30)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait(timeout=10)
    return {"label": label, "status": "PASS", "returncode": process.returncode}


def clean_transport_env() -> dict[str, str]:
    env = dict(os.environ)
    for name in (
        "MC_USE_NVLINK_IPC",
        "MC_FORCE_MNNVL",
        "MC_FORCE_TCP",
        "MC_FORCE_HCA",
        "MC_INTRANODE_NVLINK",
        "MOONCAKE_CONFIG_PATH",
    ):
        env.pop(name, None)
    env["MC_MS_AUTO_DISC"] = "1"
    return env


def local_memcpy_baseline(
    length: int = 512 * 1024**2, samples: int = 10
) -> dict[str, object]:
    source = mmap.mmap(-1, length)
    destination = mmap.mmap(-1, length)
    try:
        src = ctypes.addressof(ctypes.c_char.from_buffer(source))
        dst = ctypes.addressof(ctypes.c_char.from_buffer(destination))
        libc = ctypes.CDLL(None)
        libc.memcpy.argtypes = [ctypes.c_void_p, ctypes.c_void_p, ctypes.c_size_t]
        libc.memcpy.restype = ctypes.c_void_p
        libc.memset.argtypes = [ctypes.c_void_p, ctypes.c_int, ctypes.c_size_t]
        libc.memset.restype = ctypes.c_void_p
        libc.memset(src, 0xA5, length)
        libc.memset(dst, 0, length)
        libc.memcpy(dst, src, length)
        bandwidths: list[float] = []
        latencies: list[float] = []
        for _ in range(samples):
            started = time.perf_counter_ns()
            libc.memcpy(dst, src, length)
            duration = time.perf_counter_ns() - started
            latencies.append(float(duration))
            bandwidths.append(length * 1e9 / duration / 1e9)
        return {
            "path": "LOCAL_HOST_MEMCPY",
            "bytes": length,
            "bandwidth_gb_s": summarize(bandwidths),
            "duration_ns": summarize(latencies),
        }
    finally:
        source.close()
        destination.close()


def parse_te_benchmark(output: str) -> dict[str, float]:
    match = re.search(
        r"Test completed: duration\s+([0-9.]+), batch count\s+(\d+), throughput\s+([0-9.]+)\s+GB/s",
        output,
    )
    if match is None:
        raise RuntimeError("transfer_engine_bench did not emit a throughput summary")
    duration = float(match.group(1))
    batches = int(match.group(2))
    return {
        "duration_seconds": duration,
        "batch_count": batches,
        "bandwidth_gb_s": float(match.group(3)),
        "mean_completion_ns": duration * 1e9 / batches if batches > 0 else 0.0,
    }


def parse_te_latency_samples(output: str) -> list[float]:
    return [
        float(value)
        for value in re.findall(r"Latency sample: duration\s+(\d+)\s+ns", output)
    ]


def free_consumer_port_base(address: str, devices: list[int], start: int) -> int:
    for base in range(start, 65536 - max(devices)):
        sockets: list[socket.socket] = []
        try:
            for device in devices:
                sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
                sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
                sock.bind((address, base + device))
                sockets.append(sock)
            return base
        except OSError:
            pass
        finally:
            for sock in sockets:
                sock.close()
    raise RuntimeError("no free Consumer port range was found")


def run_rdma_case(
    binary: pathlib.Path,
    manifest: Mapping[str, object],
    local_ip: str,
    operation: str,
    block_size: int,
    threads: int,
    duration: int,
    batch_size: int,
    latency_iterations: int = 0,
) -> dict[str, object]:
    local_port = free_port(local_ip, 13000)
    command = [
        str(binary),
        "--mode=initiator",
        "--protocol=rdma",
        "--auto_discovery=true",
        "--use_vram=false",
        f"--metadata_server={manifest['metadata_server']}",
        f"--local_server_name={local_ip}:{local_port}",
        f"--segment_id={manifest['rdma_target']}",
        f"--operation={operation}",
        f"--block_size={block_size}",
        f"--batch_size={batch_size}",
        f"--threads={threads}",
        f"--duration={duration}",
        f"--latency_iterations={latency_iterations}",
        "--buffer_size=4294967296",
        "--report_unit=GB",
        "--report_precision=6",
    ]
    usage_before = resource.getrusage(resource.RUSAGE_CHILDREN)
    wall_started = time.monotonic()
    completed = run(
        command,
        env=clean_transport_env(),
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
    )
    wall_seconds = time.monotonic() - wall_started
    usage_after = resource.getrusage(resource.RUSAGE_CHILDREN)
    if completed.returncode != 0:
        raise RuntimeError(
            f"RDMA {operation} case failed rc={completed.returncode}:\n{completed.stdout[-8000:]}"
        )
    result: dict[str, object] = {
        "path": "KVPOOL_HOST_H2H_RDMA",
        "operation": operation,
        "block_size": block_size,
        "threads": threads,
        "batch_size": batch_size,
        "cpu_seconds": (
            usage_after.ru_utime
            + usage_after.ru_stime
            - usage_before.ru_utime
            - usage_before.ru_stime
        ),
        "aggregate_cpu_utilization_percent": (
            100.0
            * (
                usage_after.ru_utime
                + usage_after.ru_stime
                - usage_before.ru_utime
                - usage_before.ru_stime
            )
            / wall_seconds
            if wall_seconds > 0
            else 0.0
        ),
    }
    if latency_iterations > 0:
        samples = parse_te_latency_samples(completed.stdout)
        if len(samples) != latency_iterations:
            raise RuntimeError(
                f"RDMA latency expected {latency_iterations} samples, got "
                f"{len(samples)}"
            )
        result["latency_samples_ns"] = samples
        result["duration_ns"] = summarize(samples)
    else:
        result.update(parse_te_benchmark(completed.stdout))
    return result


def run_rdma_matrix(
    binary: pathlib.Path, manifest: Mapping[str, object], local_ip: str
) -> dict[str, object]:
    before = collect_rdma_counters()
    scans: list[dict[str, object]] = []
    sustained: list[dict[str, object]] = []
    latency: list[dict[str, object]] = []
    for operation in ("read", "write"):
        for block_size in RDMA_BLOCKS:
            batch_size = max(1, min(128, (512 * 1024**2) // block_size // 8))
            for threads in RDMA_THREADS:
                scans.append(
                    run_rdma_case(
                        binary,
                        manifest,
                        local_ip,
                        operation,
                        block_size,
                        threads,
                        3,
                        batch_size,
                    )
                )
        operation_scans = [item for item in scans if item["operation"] == operation]
        best = max(operation_scans, key=lambda item: float(item["bandwidth_gb_s"]))
        sustained_cases = [
            run_rdma_case(
                binary,
                manifest,
                local_ip,
                operation,
                int(best["block_size"]),
                int(best["threads"]),
                10,
                int(best["batch_size"]),
            )
            for _ in range(3)
        ]
        sustained.append(
            {
                "path": "KVPOOL_HOST_H2H_RDMA",
                "operation": operation,
                "block_size": int(best["block_size"]),
                "threads": int(best["threads"]),
                "batch_size": int(best["batch_size"]),
                "runs": sustained_cases,
                "bandwidth_gb_s": summarize(
                    float(item["bandwidth_gb_s"]) for item in sustained_cases
                ),
                "bandwidth_gib_s": summarize(
                    float(item["bandwidth_gb_s"]) * 1e9 / 1024**3
                    for item in sustained_cases
                ),
                "aggregate_cpu_utilization_percent": summarize(
                    float(item["aggregate_cpu_utilization_percent"])
                    for item in sustained_cases
                ),
            }
        )
        for block_size in (64, 4096):
            value = run_rdma_case(
                binary,
                manifest,
                local_ip,
                operation,
                block_size,
                1,
                0,
                1,
                latency_iterations=33,
            )
            steady_samples = list(value["latency_samples_ns"])[3:]
            latency.append(
                {
                    "path": "KVPOOL_HOST_H2H_RDMA",
                    "operation": operation,
                    "bytes": block_size,
                    "semantic": (
                        "host-submitted RNIC request-completion latency; first "
                        "three endpoint warmup samples excluded"
                    ),
                    "warmups": 3,
                    "duration_ns": summarize(steady_samples),
                }
            )
    after = collect_rdma_counters()
    delta = counter_delta(before, after)
    data_delta = sum(
        value
        for name, value in delta.items()
        if name.endswith(("port_xmit_data", "port_rcv_data")) and value > 0
    )
    data_delta_by_counter = {
        counter: sum(
            value
            for name, value in delta.items()
            if name.endswith(counter) and value > 0
        )
        for counter in ("port_xmit_data", "port_rcv_data")
    }
    error_delta = sum(
        value
        for name, value in delta.items()
        if name.endswith(
            (
                "port_xmit_discards",
                "port_rcv_errors",
                "symbol_error",
                "link_downed",
                "link_error_recovery",
            )
        )
        and value > 0
    )
    return {
        "path": "KVPOOL_HOST_H2H_RDMA",
        "control_plane": "Host CPU",
        "data_mover": "RNIC DMA",
        "scan": scans,
        "sustained": sustained,
        "latency": latency,
        "rdma_counter_delta": delta,
        "route_status": (
            "PASS"
            if all(value > 0 for value in data_delta_by_counter.values())
            and error_delta == 0
            else "FAIL"
        ),
        "positive_data_counter_delta": data_delta,
        "positive_data_counter_delta_by_direction": data_delta_by_counter,
        "positive_data_bytes_estimate": data_delta * 4,
        "positive_error_counter_delta": error_delta,
    }


def raw_summaries(records: list[dict[str, object]]) -> dict[str, object]:
    samples = [item for item in records if item.get("event") == "raw_bandwidth_sample"]
    cases: list[dict[str, object]] = []
    keys = sorted(
        {
            (
                str(item["group"]),
                str(item["path"]),
                str(item["engine"]),
                int(item["device"]),
                int(item["bytes"]),
                int(item["streams"]),
            )
            for item in samples
        }
    )
    for group, path, engine, device, byte_count, streams in keys:
        values = [
            float(item["bandwidth_gb_s"])
            for item in samples
            if (
                item["group"],
                item["path"],
                item["engine"],
                int(item["device"]),
                int(item["bytes"]),
                int(item["streams"]),
            )
            == (group, path, engine, device, byte_count, streams)
        ]
        durations = [
            float(item["duration_seconds"])
            for item in samples
            if (
                item["group"],
                item["path"],
                item["engine"],
                int(item["device"]),
                int(item["bytes"]),
                int(item["streams"]),
            )
            == (group, path, engine, device, byte_count, streams)
        ]
        summary = summarize(values)
        cases.append(
            {
                "scope": "device",
                "group": group,
                "path": path,
                "engine": engine,
                "device": device,
                "bytes": byte_count,
                "streams": streams,
                "bandwidth_gb_s": summary,
                "minimum_window_seconds": min(durations),
                "stable": float(summary["cv"]) <= 0.05 and min(durations) >= 1.0,
            }
        )
    aggregates = [
        item for item in records if item.get("event") == "raw_aggregate_sample"
    ]
    aggregate_keys = sorted(
        {
            (
                str(item["group"]),
                str(item["path"]),
                str(item["engine"]),
                int(item["bytes_per_device"]),
                int(item["streams"]),
            )
            for item in aggregates
        }
    )
    for group, path, engine, byte_count, streams in aggregate_keys:
        values = [
            float(item["aggregate_bandwidth_gb_s"])
            for item in aggregates
            if (
                item["group"],
                item["path"],
                item["engine"],
                int(item["bytes_per_device"]),
                int(item["streams"]),
            )
            == (group, path, engine, byte_count, streams)
        ]
        durations = [
            float(item["duration_seconds"])
            for item in aggregates
            if (
                item["group"],
                item["path"],
                item["engine"],
                int(item["bytes_per_device"]),
                int(item["streams"]),
            )
            == (group, path, engine, byte_count, streams)
        ]
        summary = summarize(values)
        cases.append(
            {
                "scope": "aggregate",
                "group": group,
                "path": path,
                "engine": engine,
                "device": "aggregate",
                "bytes": byte_count,
                "streams": streams,
                "bandwidth_gb_s": summary,
                "minimum_window_seconds": min(durations),
                "stable": float(summary["cv"]) <= 0.05 and min(durations) >= 1.0,
            }
        )
    ceilings: list[dict[str, object]] = []
    ceiling_keys = sorted(
        {
            (
                str(case["scope"]),
                str(case["group"]),
                str(case["path"]),
                str(case["engine"]),
                str(case["device"]),
            )
            for case in cases
        }
    )
    for scope, group, path, engine, device in ceiling_keys:
        matrix = [
            case
            for case in cases
            if case["scope"] == scope
            and case["group"] == group
            and case["path"] == path
            and case["engine"] == engine
            and str(case["device"]) == device
        ]
        stable = [case for case in matrix if case["stable"]]
        if not stable:
            ceilings.append(
                {
                    "scope": scope,
                    "group": group,
                    "path": path,
                    "engine": engine,
                    "device": device,
                    "status": "UNSTABLE",
                }
            )
            continue
        configured_max_payload = max(int(case["bytes"]) for case in matrix)
        configured_max_streams = max(int(case["streams"]) for case in matrix)
        matrix_edge = next(
            (
                case
                for case in matrix
                if int(case["bytes"]) == configured_max_payload
                and int(case["streams"]) == configured_max_streams
            ),
            None,
        )
        if matrix_edge is None or not matrix_edge["stable"]:
            ceilings.append(
                {
                    "scope": scope,
                    "group": group,
                    "path": path,
                    "engine": engine,
                    "device": device,
                    "status": "UNSTABLE_MATRIX_EDGE",
                    "matrix_edge_case": matrix_edge,
                }
            )
            continue
        best = max(stable, key=lambda item: float(item["bandwidth_gb_s"]["p50"]))
        best_value = float(best["bandwidth_gb_s"]["p50"])
        plateau = min(
            (
                case
                for case in stable
                if float(case["bandwidth_gb_s"]["p50"]) >= 0.97 * best_value
            ),
            key=lambda item: (int(item["bytes"]), int(item["streams"])),
        )
        by_coordinate = {
            (int(case["bytes"]), int(case["streams"])): case for case in stable
        }
        edge_improvements: list[float] = []
        payloads = sorted({int(case["bytes"]) for case in stable})
        streams = sorted({int(case["streams"]) for case in stable})
        if len(payloads) >= 2:
            for stream_count in streams:
                previous = by_coordinate.get((payloads[-2], stream_count))
                edge = by_coordinate.get((payloads[-1], stream_count))
                if previous and edge:
                    edge_improvements.append(
                        float(edge["bandwidth_gb_s"]["p50"])
                        / float(previous["bandwidth_gb_s"]["p50"])
                        - 1.0
                    )
        if len(streams) >= 2:
            for payload in payloads:
                previous = by_coordinate.get((payload, streams[-2]))
                edge = by_coordinate.get((payload, streams[-1]))
                if previous and edge:
                    edge_improvements.append(
                        float(edge["bandwidth_gb_s"]["p50"])
                        / float(previous["bandwidth_gb_s"]["p50"])
                        - 1.0
                    )
        maximum_edge_improvement = max(edge_improvements, default=0.0)
        status = (
            "UNBOUNDED_BY_MATRIX" if maximum_edge_improvement > 0.03 else "QUALIFIED"
        )
        ceilings.append(
            {
                "scope": scope,
                "group": group,
                "path": path,
                "engine": engine,
                "device": device,
                "status": status,
                "measured_ceiling_gb_s": best_value,
                "c2c_450gb_s_utilization": best_value / 450.0,
                "best": best,
                "smallest_97_percent_plateau": plateau,
                "maximum_matrix_edge_improvement": maximum_edge_improvement,
            }
        )
    latency_records = [
        item
        for item in records
        if item.get("event") in {"memory_latency_sample", "egm_h2h_latency_sample"}
    ]
    latency: list[dict[str, object]] = []
    latency_keys = sorted(
        {
            (
                str(item.get("memory_kind", item.get("direction"))),
                int(item["device"]),
                int(item["working_set_bytes"]),
                str(item["event"]),
            )
            for item in latency_records
        }
    )
    for kind, device, working_set, event in latency_keys:
        matching = [
            item
            for item in latency_records
            if str(item.get("memory_kind", item.get("direction"))) == kind
            and int(item["device"]) == device
            and int(item["working_set_bytes"]) == working_set
            and item["event"] == event
        ]
        fields = sorted(
            name
            for name in matching[0]
            if name.endswith(("cycles_per_op", "ns_per_op"))
        )
        latency.append(
            {
                "kind": kind,
                "device": device,
                "working_set_bytes": working_set,
                "event": event,
                "gpu_clock_khz": matching[0].get("gpu_clock_khz"),
                **{
                    field: summarize(float(item[field]) for item in matching)
                    for field in fields
                },
            }
        )
    gates = [item for item in records if item.get("event") == "raw_benchmark_gate"]
    required_ceilings = [
        ceiling
        for ceiling in ceilings
        if ceiling["scope"] == "aggregate"
        and ceiling["path"] in {"EGM_H2D", "EGM_D2H"}
        and ceiling["engine"] == "CE"
    ]
    gate_pass = len(gates) == 1 and gates[0].get("status") == "PASS"
    ceiling_pass = bool(required_ceilings) and all(
        ceiling["status"] == "QUALIFIED" for ceiling in required_ceilings
    )
    return {
        "status": "PASS" if gate_pass and ceiling_pass else "FAIL",
        "correctness_status": "PASS" if gate_pass else "FAIL",
        "ceiling_status": "PASS" if ceiling_pass else "FAIL",
        "aggregate_cases": [case for case in cases if case["scope"] == "aggregate"],
        "ceilings": ceilings,
        "latency": latency,
    }


def store_summary(path: pathlib.Path) -> dict[str, object]:
    records = read_jsonl(path)
    gates = [item for item in records if item.get("event") == "benchmark_gate"]
    return {
        "status": "PASS"
        if len(gates) == 1 and gates[0].get("status") == "PASS"
        else "FAIL",
        "gate": gates[0] if len(gates) == 1 else None,
        "performance": [
            item
            for item in records
            if item.get("event") in {"performance_summary", "aggregate_iteration"}
            and item.get("sequence_phase") == "steady"
        ],
    }


def run_raw_benchmark(
    binary: pathlib.Path,
    manifest: Mapping[str, object],
    devices: list[int],
    result_dir: pathlib.Path,
) -> tuple[dict[str, object], dict[str, object]]:
    raw_log = result_dir / "raw-egm.jsonl"
    raw_stderr = result_dir / "raw-egm.stderr.log"
    h2h_log = result_dir / "raw-egm-h2h.jsonl"
    h2h_stderr = result_dir / "raw-egm-h2h.stderr.log"
    base_command = [
        str(binary),
        f"--metadata_server={manifest['metadata_server']}",
        f"--segment_name={manifest['provider_hostname']}",
        f"--devices={','.join(str(device) for device in devices)}",
        f"--payload_sizes={','.join(str(value) for value in RAW_PAYLOADS)}",
        f"--stream_counts={','.join(str(value) for value in RAW_STREAMS)}",
        "--warmups=3",
        "--samples=10",
        "--min_window_seconds=1",
        "--latency_accesses=262144",
        "--latency_samples=30",
        "--latency_working_sets=2097152,268435456,1073741824",
        f"--run_id={manifest['run_id']}",
        f"--source_sha={manifest['source_sha']}",
    ]
    mandatory_command = [*base_command, "--paths=H2D,D2H", "--run_latency=true"]
    h2h_command = [
        *base_command,
        "--paths=H2H_LOCAL_TO_REMOTE,H2H_REMOTE_TO_LOCAL",
        "--run_latency=false",
    ]
    route_before = collect_route_snapshot()
    with (
        raw_log.open("w") as output,
        raw_stderr.open("w") as errors,
        h2h_log.open("w") as h2h_output,
        h2h_stderr.open("w") as h2h_errors,
    ):
        mandatory_completed = run(
            mandatory_command,
            env=clean_transport_env(),
            check=False,
            stdout=output,
            stderr=errors,
        )
        route_mandatory_after = collect_route_snapshot()
        h2h_completed = run(
            h2h_command,
            env=clean_transport_env(),
            check=False,
            stdout=h2h_output,
            stderr=h2h_errors,
        )
    route_after = collect_route_snapshot()
    records = read_jsonl(raw_log)
    summary = raw_summaries(records)
    if mandatory_completed.returncode != 0:
        summary["status"] = "FAIL"
        summary["returncode"] = mandatory_completed.returncode
    h2h_records = read_jsonl(h2h_log)
    h2h_summary = raw_summaries(h2h_records)
    h2h_gates = [
        item for item in h2h_records if item.get("event") == "raw_benchmark_gate"
    ]
    h2h_execution_pass = (
        h2h_completed.returncode == 0
        and len(h2h_gates) == 1
        and h2h_gates[0].get("status") == "PASS"
    )
    h2h_summary["returncode"] = h2h_completed.returncode
    summary["supplementary_h2h"] = h2h_summary
    route = build_route_evidence(
        route_before,
        route_mandatory_after,
        "Node B HBM-to/from-remote-EGM NVLink traffic with inferred C2C route",
    )
    h2h_summary["route"] = build_route_evidence(
        route_mandatory_after,
        route_after,
        "host-submitted, GPU-CE/SM-executed EGM H2H route evidence",
    )
    h2h_summary["status"] = (
        "PASS"
        if h2h_execution_pass and h2h_summary["route"]["status"] == "PASS"
        else "UNSUPPORTED_OR_ROUTE_UNVERIFIED"
    )
    return summary, route


def provider_mode(args: argparse.Namespace) -> int:
    script_dir = pathlib.Path(__file__).resolve().parent
    repo_root = script_dir.parent.parent
    wrapper = script_dir / "egm_store_gb200.sh"
    source_sha = git_value(repo_root, "rev-parse", "HEAD")
    source_branch = git_value(repo_root, "branch", "--show-current")
    run_id = f"gb200-{time.strftime('%Y%m%d-%H%M%S')}-{source_sha[:8]}-{secrets.token_hex(3)}"
    result_root = pathlib.Path(args.result_root)
    result_dir = result_root / run_id
    result_dir.mkdir(parents=True, exist_ok=False)
    build_dir = pathlib.Path(args.build_dir or repo_root / "build-egm-store-gb200")
    used = {args.bootstrap_port}
    ports = {
        "master_rpc": free_port(args.listen_ip, 50051, used),
        "master_admin": free_port(args.listen_ip, 9003, used),
        "provider": free_port(args.listen_ip, 12345, used),
        "rdma_target": free_port(args.listen_ip, 12500, used),
    }
    config_values: dict[str, object] = {
        "NODE_A_IP": args.listen_ip,
        "NODE_B_IP": "127.0.0.1",
        "RUN_ID": run_id,
        "BUILD_DIR": str(build_dir),
        "RESULT_ROOT": str(result_root),
        "MASTER_RPC_PORT": ports["master_rpc"],
        "MASTER_ADMIN_PORT": ports["master_admin"],
        "METADATA_PORT": args.bootstrap_port,
        "PROVIDER_PORT": ports["provider"],
        "CONSUMER_PORT_BASE": 12400,
        "EGM_POOL_SIZE": "20 GB",
        "EGM_NUMA_NODES": "auto",
        "MC_MAX_MR_SIZE_BYTES": 157286400,
        "MC_IMEX_DAEMON_EXTERNAL": 1,
        "DEVICES": "0,1,2,3",
        "PAYLOAD_SIZES": ",".join(str(value) for value in DEFAULT_PAYLOADS),
        "ITERATIONS": 13,
        "STORE_WARMUPS": 2,
        "THRESHOLD_PAYLOAD_SIZE": 2 * 1024**3,
        "MIN_PUT_GIB_S": 0,
        "MIN_GET_GIB_S": 0,
        "BUILD_UNIT_TESTS": 0,
        "MASTER_START_TIMEOUT_SEC": 30,
        "PROVIDER_READINESS_TIMEOUT_SEC": 180,
    }
    config_path = result_dir / "generated.conf"
    write_config(config_path, config_values)
    metadata_base = f"http://{args.listen_ip}:{args.bootstrap_port}/metadata"
    token = secrets.token_hex(24)
    rdma_process: subprocess.Popen[str] | None = None
    rdma_log = None
    status = "FAIL"
    error = "provider orchestration did not complete"
    completion: dict[str, object] | None = None
    cleanup: list[dict[str, object]] = []
    local_memcpy: dict[str, object] = {"status": "NOT_RUN"}
    provider_started = False
    stop_requested = False

    def request_stop(_signum, _frame):
        nonlocal stop_requested
        stop_requested = True

    signal.signal(signal.SIGINT, request_stop)
    signal.signal(signal.SIGTERM, request_stop)
    system_before = collect_system()
    route_before = collect_route_snapshot()
    try:
        if not args.skip_build:
            run([str(wrapper), "--config", str(config_path), "build"], cwd=repo_root)
        run([str(wrapper), "--config", str(config_path), "preflight"], cwd=repo_root)
        local_memcpy = local_memcpy_baseline()
        run([str(wrapper), "--config", str(config_path), "master-start"], cwd=repo_root)
        run(
            [str(wrapper), "--config", str(config_path), "provider-start"],
            cwd=repo_root,
        )
        provider_started = True
        rdma_binary = (
            build_dir / "mooncake-transfer-engine/example/transfer_engine_bench"
        )
        rdma_log_path = result_dir / "rdma-target.log"
        rdma_log = rdma_log_path.open("w")
        rdma_env = clean_transport_env()
        rdma_env["MC_TCP_BIND_ADDRESS"] = args.listen_ip
        rdma_process = subprocess.Popen(
            [
                str(rdma_binary),
                "--mode=target",
                "--protocol=rdma",
                "--auto_discovery=true",
                "--use_vram=false",
                f"--metadata_server={metadata_base}",
                f"--local_server_name={args.listen_ip}:{ports['rdma_target']}",
                "--buffer_size=4294967296",
            ],
            env=rdma_env,
            text=True,
            stdout=rdma_log,
            stderr=subprocess.STDOUT,
        )
        wait_process_log_marker(
            rdma_process,
            rdma_log_path,
            RDMA_TARGET_READY_MARKER,
            "RDMA target",
            120,
        )
        manifest: dict[str, object] = {
            "schema": "MOONCAKE_GB200_SESSION_V1",
            "run_id": run_id,
            "token": token,
            "source_sha": source_sha,
            "source_branch": source_branch,
            "node_a_ip": args.listen_ip,
            "bootstrap_port": args.bootstrap_port,
            "metadata_server": metadata_base,
            "master_server": f"{args.listen_ip}:{ports['master_rpc']}",
            "master_admin_url": f"http://{args.listen_ip}:{ports['master_admin']}",
            "provider_hostname": f"{args.listen_ip}:{ports['provider']}",
            "rdma_target": f"{args.listen_ip}:{ports['rdma_target']}",
            "config": {
                "store_payloads": DEFAULT_PAYLOADS,
                "raw_payloads": RAW_PAYLOADS,
                "raw_streams": RAW_STREAMS,
                "store_iterations": 13,
                "store_warmups": 2,
            },
        }
        manifest["config_digest"] = config_digest(manifest["config"])
        metadata_delete(metadata_base, ACTIVE_SESSION_KEY)
        metadata_put(metadata_base, ACTIVE_SESSION_KEY, manifest)
        completion_key = f"mooncake/gb200-validation/{run_id}/completion"
        metadata_delete(metadata_base, completion_key)
        print("\nGB200 validation Provider READY", flush=True)
        print("Run the following command on Node B:\n", flush=True)
        print(
            f"scripts/gb200/egm_store_gb200.sh full-consumer "
            f"--provider http://{args.listen_ip}:{args.bootstrap_port}",
            flush=True,
        )
        deadline = time.monotonic() + args.timeout_sec
        while time.monotonic() < deadline and not stop_requested:
            completion = metadata_get(metadata_base, completion_key)
            if completion is not None:
                if completion.get("token") != token:
                    raise RuntimeError("completion token mismatch")
                expected_completion = {
                    "run_id": run_id,
                    "source_sha": source_sha,
                    "config_digest": manifest["config_digest"],
                }
                mismatches = {
                    name: (expected, completion.get(name))
                    for name, expected in expected_completion.items()
                    if completion.get(name) != expected
                }
                if mismatches:
                    raise RuntimeError(f"completion manifest mismatch: {mismatches}")
                break
            if rdma_process.poll() is not None:
                raise RuntimeError(f"RDMA target exited rc={rdma_process.returncode}")
            time.sleep(2)
        if completion is None:
            raise RuntimeError("timed out or interrupted while waiting for Node B")
        status = "PASS" if completion.get("status") == "PASS" else "FAIL"
        error = str(completion.get("error", ""))
    except (Exception, KeyboardInterrupt) as exc:
        error = str(exc)
    finally:
        cleanup.append(stop_process(rdma_process, "rdma_target"))
        if rdma_log is not None:
            rdma_log.close()
        try:
            run(
                [str(wrapper), "--config", str(config_path), "provider-stop"],
                cwd=repo_root,
            )
            cleanup.append({"label": "store_provider", "status": "PASS"})
        except subprocess.CalledProcessError as exc:
            cleanup.append(
                {"label": "store_provider", "status": "FAIL", "error": str(exc)}
            )
            status = "FAIL"
        try:
            run(
                [str(wrapper), "--config", str(config_path), "master-stop"],
                cwd=repo_root,
            )
            cleanup.append({"label": "master", "status": "PASS"})
        except subprocess.CalledProcessError as exc:
            cleanup.append({"label": "master", "status": "FAIL", "error": str(exc)})
            status = "FAIL"
    if provider_started and completion is not None:
        route_after = collect_route_snapshot()
        route_evidence = build_route_evidence(
            route_before,
            route_after,
            "Node A remote-EGM endpoint NVLink traffic with inferred C2C route",
        )
    else:
        route_evidence = {
            "status": "NOT_RUN",
            "route_verification": "C2C_ROUTE_INFERRED",
            "reason": (
                "Store Provider did not start"
                if not provider_started
                else "No validated Consumer completion was received"
            ),
        }
    if status == "PASS" and route_evidence["status"] != "PASS":
        status = "FAIL"
        error = "Node A C2C/NVLink route evidence is incomplete or contains errors"
    evidence = {
        "schema": "MOONCAKE_GB200_EVIDENCE_V1",
        "role": "A",
        "status": status,
        "error": error if status != "PASS" else "",
        "run_id": run_id,
        "source_sha": source_sha,
        "source_branch": source_branch,
        "config_digest": (completion.get("config_digest") if completion else None),
        "system_before": system_before,
        "system_after": collect_system(),
        "local_host_memcpy": local_memcpy,
        "egm_route": route_evidence,
        "completion": completion,
        "cleanup": cleanup,
        "artifacts": artifact_manifest(result_dir),
    }
    (result_dir / "node-a-evidence.json").write_text(
        json.dumps(evidence, sort_keys=True) + "\n"
    )
    emit_evidence(evidence)
    return 0 if status == "PASS" else 1


def consumer_mode(args: argparse.Namespace) -> int:
    script_dir = pathlib.Path(__file__).resolve().parent
    repo_root = script_dir.parent.parent
    wrapper = script_dir / "egm_store_gb200.sh"
    parsed = urllib.parse.urlparse(args.provider)
    if parsed.scheme != "http" or not parsed.hostname or not parsed.port:
        raise SystemExit("--provider must be an http://host:port bootstrap URL")
    metadata_base = f"{args.provider.rstrip('/')}/metadata"
    manifest = metadata_get(metadata_base, ACTIVE_SESSION_KEY)
    if manifest is None:
        raise SystemExit("Node A has no active GB200 validation session")
    required = {
        "run_id",
        "token",
        "source_sha",
        "config_digest",
        "metadata_server",
        "master_server",
        "provider_hostname",
        "rdma_target",
    }
    missing = sorted(required - manifest.keys())
    if missing:
        raise SystemExit(f"Node A session manifest is missing {missing}")
    source_sha = git_value(repo_root, "rev-parse", "HEAD")
    if source_sha != manifest["source_sha"]:
        mismatch_error = (
            f"source SHA mismatch: local={source_sha} node-a={manifest['source_sha']}"
        )
        metadata_put(
            metadata_base,
            f"mooncake/gb200-validation/{manifest['run_id']}/completion",
            {
                "status": "FAIL",
                "error": mismatch_error,
                "run_id": manifest["run_id"],
                "token": manifest["token"],
                "source_sha": manifest["source_sha"],
                "config_digest": manifest["config_digest"],
            },
        )
        raise SystemExit(
            mismatch_error + "\n"
            "Run: git fetch neverhook codex/egm-store-pool-gb200-validation && "
            "git switch --detach FETCH_HEAD"
        )
    local_ip = route_address(parsed.hostname)
    run_id = str(manifest["run_id"])
    result_root = pathlib.Path(args.result_root)
    result_dir = result_root / run_id
    result_dir.mkdir(parents=True, exist_ok=True)
    build_dir = pathlib.Path(args.build_dir or repo_root / "build-egm-store-gb200")
    devices = visible_devices()[:4]
    consumer_base = free_consumer_port_base(local_ip, devices, 12400)
    config_values: dict[str, object] = {
        "NODE_A_IP": parsed.hostname,
        "NODE_B_IP": local_ip,
        "RUN_ID": run_id,
        "BUILD_DIR": str(build_dir),
        "RESULT_ROOT": str(result_root),
        "MASTER_RPC_PORT": int(str(manifest["master_server"]).rsplit(":", 1)[1]),
        "MASTER_ADMIN_PORT": int(
            urllib.parse.urlparse(str(manifest["master_admin_url"])).port or 9003
        ),
        "METADATA_PORT": parsed.port,
        "PROVIDER_PORT": int(str(manifest["provider_hostname"]).rsplit(":", 1)[1]),
        "CONSUMER_PORT_BASE": consumer_base,
        "EGM_POOL_SIZE": "20 GB",
        "EGM_NUMA_NODES": "auto",
        "MC_MAX_MR_SIZE_BYTES": 157286400,
        "MC_IMEX_DAEMON_EXTERNAL": 1,
        "DEVICES": ",".join(str(device) for device in devices),
        "PAYLOAD_SIZES": ",".join(str(value) for value in DEFAULT_PAYLOADS),
        "ITERATIONS": 13,
        "STORE_WARMUPS": 2,
        "THRESHOLD_PAYLOAD_SIZE": 2 * 1024**3,
        "MIN_PUT_GIB_S": 0,
        "MIN_GET_GIB_S": 0,
        "BUILD_UNIT_TESTS": 0,
        "MASTER_START_TIMEOUT_SEC": 30,
        "PROVIDER_READINESS_TIMEOUT_SEC": 180,
        "MC_EGM_VALIDATION_CUDA_LIBRARY": str(
            build_dir / "mooncake-transfer-engine/example/libegm_validation_cuda.so"
        ),
    }
    config_path = result_dir / "generated-node-b.conf"
    write_config(config_path, config_values)
    status = "FAIL"
    error = "consumer orchestration did not complete"
    raw: dict[str, object] = {"status": "NOT_RUN"}
    raw_route: dict[str, object] = {"status": "NOT_RUN"}
    rdma: dict[str, object] = {"status": "NOT_RUN"}
    store: dict[str, object] = {"status": "NOT_RUN"}
    local_memcpy: dict[str, object] = {"status": "NOT_RUN"}
    system_before = collect_system()
    completion_key = f"mooncake/gb200-validation/{run_id}/completion"
    try:
        if not args.skip_build:
            run([str(wrapper), "--config", str(config_path), "build"], cwd=repo_root)
        run([str(wrapper), "--config", str(config_path), "preflight"], cwd=repo_root)
        local_memcpy = local_memcpy_baseline()
        raw_binary = build_dir / "mooncake-transfer-engine/example/egm_link_bench"
        raw, raw_route = run_raw_benchmark(raw_binary, manifest, devices, result_dir)
        rdma_binary = (
            build_dir / "mooncake-transfer-engine/example/transfer_engine_bench"
        )
        rdma = run_rdma_matrix(rdma_binary, manifest, local_ip)
        store_route_before = collect_route_snapshot()
        run([str(wrapper), "--config", str(config_path), "bench"], cwd=repo_root)
        store_route_after = collect_route_snapshot()
        store = store_summary(result_dir / "bench.jsonl")
        store["route"] = build_route_evidence(
            store_route_before,
            store_route_after,
            "Node B Store HBM-to/from-remote-EGM NVLink traffic with inferred C2C route",
        )
        if store["route"]["status"] != "PASS":
            store["status"] = "FAIL"
        mandatory = [
            raw.get("status"),
            raw_route.get("status"),
            rdma.get("route_status"),
            store.get("status"),
        ]
        if mandatory != ["PASS", "PASS", "PASS", "PASS"]:
            raise RuntimeError(f"mandatory validation gate failed: {mandatory}")
        status = "PASS"
        error = ""
    except (Exception, KeyboardInterrupt) as exc:
        error = str(exc)
    evidence = {
        "schema": "MOONCAKE_GB200_EVIDENCE_V1",
        "role": "B",
        "status": status,
        "error": error,
        "run_id": run_id,
        "source_sha": source_sha,
        "source_branch": git_value(repo_root, "branch", "--show-current"),
        "config_digest": manifest["config_digest"],
        "system_before": system_before,
        "system_after": collect_system(),
        "local_host_memcpy": local_memcpy,
        "kvpool_host_h2h_rdma": rdma,
        "egm_raw": raw,
        "egm_route": raw_route,
        "store": store,
        "artifacts": artifact_manifest(result_dir),
    }
    evidence_path = result_dir / "node-b-evidence.json"
    evidence_path.write_text(json.dumps(evidence, sort_keys=True) + "\n")
    completion = {
        "status": status,
        "error": error,
        "run_id": run_id,
        "token": manifest["token"],
        "source_sha": source_sha,
        "config_digest": manifest["config_digest"],
        "node_b_evidence_sha256": hashlib_file(evidence_path),
        "node_b_evidence_path": str(evidence_path),
    }
    try:
        metadata_put(metadata_base, completion_key, completion)
    except Exception as exc:
        evidence["completion_publish_error"] = str(exc)
        evidence["status"] = "FAIL"
        status = "FAIL"
        evidence_path.write_text(json.dumps(evidence, sort_keys=True) + "\n")
    emit_evidence(evidence)
    return 0 if status == "PASS" else 1


def hashlib_file(path: pathlib.Path) -> str:
    import hashlib

    digest = hashlib.sha256()
    with path.open("rb") as source:
        while chunk := source.read(1024 * 1024):
            digest.update(chunk)
    return digest.hexdigest()


def make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="role", required=True)
    provider = subparsers.add_parser("provider")
    provider.add_argument("--listen-ip", required=True)
    provider.add_argument("--bootstrap-port", type=int, default=8079)
    provider.add_argument("--build-dir")
    provider.add_argument("--result-root", default="/tmp/mooncake-egm-gb200")
    provider.add_argument("--timeout-sec", type=int, default=6 * 60 * 60)
    provider.add_argument("--skip-build", action="store_true")
    consumer = subparsers.add_parser("consumer")
    consumer.add_argument("--provider", required=True)
    consumer.add_argument("--build-dir")
    consumer.add_argument("--result-root", default="/tmp/mooncake-egm-gb200")
    consumer.add_argument("--skip-build", action="store_true")
    return parser


def main() -> int:
    args = make_parser().parse_args()
    if args.role == "provider":
        return provider_mode(args)
    return consumer_mode(args)


if __name__ == "__main__":
    raise SystemExit(main())
